### ISSUE TITLE
Can't connect to dedicated server

### ISSUE THREAD

**Issue by mrByco** [Derek-R-S/Dark-Reflective-Mirror#10]
I tried the package with the free relay server, it worked fine, it's a great package, Then I decided to deploy our own relay server for our game. (we had 400ms ping because we connected from eu).

I can't connect to the dedicated server. I am always getting socket exception. I checked if the port was open, and it is.
What could be the solution?  The server looks fine, and the client works too (Its tested with the free server).
Here is the picture if the vps running the proxy.

![ec2-3-121-195-252 - ec2-3-121-195-252 eu-central-1 compute amazonaws com - Távoli asztali kapcsolat 2020  12  15  11_30_56](https://user-images.githubusercontent.com/20614904/102204240-e833f580-3ec9-11eb-8417-02175c52c350.png)

Or where could I search for the mistake I made?

UPDATE: I just found it in the logs, it could be helpful.
[Trace]   DarkRiftServer        System Details:
                                	OS: Microsoft Windows NT 6.2.9200.0
                                	CLS Version: 4.0.30319.42000
                                	DarkRift: 2.9.0.0 - Free
[Trace]   PluginFactory         Created plugin 'RelayPlugin'.
[Info]    PluginManager         Loaded plugin RelayPlugin version 2.5
[Trace]   PluginFactory         Created plugin 'BichannelListener'.
[Trace]   HttpHealthCheck       HTTP health check started at 'http://localhost:10666/health'
[Trace]   DarkRiftServer        Binding listeners to ClientManager as server is externally visible.
[Trace]   DefaultNetworkListener Starting bichannel listener.
[Info]    DefaultNetworkListener Server mounted, listening on port 4296.
[Trace]   DefaultNetworkListener Accepted TCP connection from 31.46.15.78:51850.
[Trace]   DefaultNetworkListener Connection attempt from 31.46.15.78:51850 timed out.
[Trace]   DefaultNetworkListener Accepted TCP connection from 31.46.15.78:51946.
[Trace]   DefaultNetworkListener Connection attempt from 31.46.15.78:51946 timed out.
[Trace]   DefaultNetworkListener Accepted TCP connection from 31.46.15.78:52211.
[Trace]   DefaultNetworkListener Connection attempt from 31.46.15.78:52211 timed out.
[Trace]   DefaultNetworkListener Accepted TCP connection from 31.46.15.78:52232.
[Trace]   DefaultNetworkListener Connection attempt from 31.46.15.78:52232 timed out.
[Trace]   DefaultNetworkListener Accepted TCP connection from 31.46.15.78:52238.
[Trace]   DefaultNetworkListener Connection attempt from 31.46.15.78:52238 timed out.

**Comment by peterparnes** [comment]
I tried connecting to your relay as well without success. It answers on telnet just like my relay but I cannot connect from Unity. Could it be some issue with the EC2-firewall blocking half of the TCP-traffic?

**Comment by mrByco** [comment]
Solved, I have set it up locally and connected to my host using my 4g net on a laptop. Now it seems to be working. 
It looks like amazon blocks udp packets for some reason.
The EC2 firewall is open for both tcp and udp traffic.
I close the issue because it is not the plugins error.

But the it can be useful for future users.
