### ISSUE TITLE
SecureKey, 'first line of defence' feature.

### ISSUE THREAD

**Issue by JesusLuvsYooh** [Derek-R-S/Dark-Reflective-Mirror#2]
1. A secure key variable, to act like a password to prevent unauthorised access, as a 'first line of defence' feature.
(simple string combo check?  eg. k93ujoej0jc)

2. Located where it is easy for new Devs to apply their own key in both places, client connect script in-game, and server.config on the Relay Server itself.
(as an example locations)

3. Optional - Outputs in relay console/text log, miss-matched key attempts, (right and wrong key for debugging comparison) and IP address (for blocking if needed.)

**Comment by Derek-R-S** [comment]
Added in latest version
